tile_offset_y : 67.86
tile_offset_x : 79.022
original_x : 9.07
original_y : -42.
points_offset_x_nogap : 6
points_offset_x_gap1 : 6.0
points_offset_x_gap2 : 6.0
points_offset_y_gap : 6.0
ref_offset_x : 0
ref_offset_y : 0
length_tile : 50.7
length_ch : 12
length_half_ch : 6
